import Footer from 'components/footer'
import Menu from 'components/menu'
import Head from 'next/head'
import HomeModel from '../models/home'
import fs from 'fs'

const Home = ({ files }) =>
  <div>
    <Head>
      <title>Icore Solutions</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Menu />
    <HomeModel gallery={files} />
    <Footer />
  </div>

export async function getStaticProps() {
  const files = fs.readdirSync("public/gallery");

  return {
    props: {
      files
    }
  }
}

export default Home